### ISSUE TITLE
Issue with special chars 

### ISSUE THREAD

**Issue by m9dfukc** [ehousestudio/craft_hacksaw#4]
Using `{{ entry.richTextField|hacksaw(words='100', append='... ') }}` I have issues with special chars. 
![image](http://i62.tinypic.com/2ylsdnk.jpg)

**Comment by ryanshrum** [comment]
Would you show me which character didn't work; I'm curious if it's a font issue over the plugin having an issue? I see that the `ä` worked fine earlier in that string.

**Comment by m9dfukc** [comment]
"Sie präsentieren souverän ..." it's an ä. In general special chars seems to work fine except if there is an special char right before hacksaw cut's the text. Funnily enough on the [live server](http://www.milla.de/jobs) (last entry on page bottom) the � won't show up but the rest of the word and the "..." are still missing; only my local developer setup the question-mark.

**Comment by joshangell** [comment]
I'm seeing similar weird issues with this. In my situation its a `’` character and as far as I can tell hacksaw is basically trying to make its cut half way through the encoded entity and I'm only thinking this because other apostrophes earlier on in the string come out fine but the breaking one is right near the end of the allowed word limit.

**Comment by joshangell** [comment]
Ok I've had a little play and come up with a sort of ok solution, I'm not sure its really great as it means each special character gets counted as a word but it at least means nothing breaks any more!

**Comment by carlcs** [comment]
There's two problems with the current fix. Text with a lot of special chars (german, french, ...) are truncated way too early. Another issue I noticed is that the counter gets messed up with each special character.

`{{ 'Gebrauchte Bücher günstig zu verkaufen'|hacksaw(words='6') }}`

Outputs "Gebrauchte Bücher günstig zu v". So both "ü" umlauts make the text been truncated by one character too late. In this example by a " " (space) and a "v".

**Comment by joshuapease** [comment]
Having a similar issue as carlcs, I'm using the words parameter, but I'm getting some leftover characters at the end of the truncated string. 

https://www.dropbox.com/s/rta1boqoqhvjkzi/Screenshot%202015-07-27%2014.07.36.png?dl=0
